import { ThemeProvider } from "@/components/theme-provider";
import { MondayContextProvider } from "@/components/monday-context-provider";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "sonner";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <MondayContextProvider>
              <div className="py-4 px-6 flex flex-col gap-4">
                {children}
              </div>
              <Toaster />
            </MondayContextProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
